# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths D:/led_ip [current_fileset]

add_files D:/lab4/lab4.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all D:/lab4/lab4.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files D:/lab4/lab4.srcs/sources_1/bd/system/system.bd]

read_vhdl -library xil_defaultlib D:/lab4/lab4.srcs/sources_1/bd/system/hdl/system_wrapper.vhd
read_xdc D:/lab4/lab4.srcs/constrs_1/imports/lab2/lab2.xdc
set_property used_in_implementation false [get_files D:/lab4/lab4.srcs/constrs_1/imports/lab2/lab2.xdc]

read_xdc D:/lab4/lab4.srcs/constrs_1/imports/lab3/lab3_system.xdc
set_property used_in_implementation false [get_files D:/lab4/lab4.srcs/constrs_1/imports/lab3/lab3_system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/lab4/lab4.cache/wt [current_project]
set_property parent.project_dir D:/lab4 [current_project]
catch { write_hwdef -file system_wrapper.hwdef }
synth_design -top system_wrapper -part xc7z010clg400-1
write_checkpoint system_wrapper.dcp
report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb
